spring.application.name=enoteserviceapis


spring.datasource.url=jdbc:mysql://127.0.0.1:3306/enotes_api
spring.datasource.username=root
spring.datasource.password=Admin@123
spring.datasource.driver=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

